# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a3efb36f7dbb62225d1bbb3715173dc7dd6bee575a64151fb9012e03da1a1eeed35446446268670aa4a967df7ba245ef50d17fb3414fb88cb5e986a5bbcc3f3
  omniauth_realme:
    customer_name: "CelebrantsOnline"
    app_name: "test"
    shared_key: 7feef0d575365443759eb860cc6eed48
    # customer_name: "RealFinance"
    # app_name: "TestApp"
    # shared_key: eb2c8fa0571f76dfcac1d18d36ed1abe
    integrator: 'https://www.cloudidentityintegrator.datacom.co.nz/service/Initiator?'

test:
  secret_key_base: 803a07d2c956ea3d52f14eb05e6e84e3c00f23790551e7d466637af601c851cf3856c0b2c53b8095710a6a7aac3e7e51e311b34c11d4d995c14092ff169a4e8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  omniauth_realme:
    customer_name: <%= ENV['REALME_CLIENT_NAME'] %>
    app_name: <%= ENV['REALME_APP_NAME'] %>
    shared_key: <%= ENV['REALME_SHARED_KEY'] %>
